apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
      env: 
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql_secret
            key: username
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql_secret
  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: mysql_service
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
