apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmysql
  labels:
    app: phpmysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmysql
  template:
    metadata:
      labels:
        app: phpmysql
    spec:
      containers:
      - name: phpmysql
        image: phpmyadmin/phpmyadmin
        env:
        - name: PMA_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: host 

--- 
apiVersion: v1
kind: Service
metadata:
  name: phpmysql-service
spec:
  ports:
  - protocol: TCP
    port: 30001
    targetPort: 80
  selector:
    app: phpmysql
  type: NodePort
